{"stats": {"errors": 1, "failures": 0, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 1}, "results": [{"classname": "index_test:BlockTest", "name": "test_target", "time": 0.0005166530609130859, "type": "error", "errtype": "builtins.NameError", "message": "name 'litte_endian_to_int' is not defined", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/sapakusa/difficulty-targets-jsong-pb-denver-070918/test/index_test.py\", line 10, in test_target\n    self.assertEqual(block.target(), 0x13ce9000000000000000000000000000000000000000000)\n  File \"/home/sapakusa/difficulty-targets-jsong-pb-denver-070918/index.ipynb\", line 103, in target\n    \"outputs\": [\nNameError: name 'litte_endian_to_int' is not defined\n"}]}